name: Publish
env:
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
    - run: npm install
    - run: npm publish
